services:
  bsky-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firehose
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - maverick
    environment:
      - BSKY_RELAY=relay1.us-east.bsky.network
      - BSKY_NATS_SERVER=nats-server:4222
      - BSKY_NATS_STREAM_NAME=bluesky
      - BSKY_NATS_MAX_STREAM_MSG=500000
      - BSKY_METRICS_PORT=9090
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
networks:
  maverick:
    external: true


